# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram

	pod 'SDWebImage'

	# add the Firebase pod for Google Analytics

	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'

	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'



end
